# .streamlit/secrets.toml
[connections.snowflake]
account = "RNVGOQR-YN20908"
user = "mkoumoudjian"
password = "andrew100!"
role = "SYSADMIN"
warehouse = "COMPUTE_WH"
database = "SMOOTHIES"
schema = "PUBLIC"
client_session_keep_alive = true
